name: mutation_fn
channels:
  - conda-forge
  - r
  - bioconda
  - defaults
dependencies:
  - r::r-base=4.0.3
  - bioconda::bioconductor-deseq2
  - ipykernel=6.6.0
  - ipython=7.30.1
  - matplotlib-base=3.5.1
  - matplotlib-venn=0.11.6
  - numpy=1.21.4
  - pandas=1.3.5
  - python=3.8.0
  - python-wget=3.2
  - scipy=1.7.3
  - seaborn=0.11.2
